using Leetcode;
//var node1 = new PalindromeLinkedListProblem.ListNode(1);
//var node2 = new PalindromeLinkedListProblem.ListNode(2);
//var node3 = new PalindromeLinkedListProblem.ListNode(2);
//var node4 = new PalindromeLinkedListProblem.ListNode(1);
//var node5 = new PalindromeLinkedListProblem.ListNode(3);
//var node6 = new PalindromeLinkedListProblem.ListNode(-2);
//var node7 = new PalindromeLinkedListProblem.ListNode(-1);
//var node8 = new PalindromeLinkedListProblem.ListNode(8);
//node1.next = node2;
//node2.next = node3;
//node3.next= node4;
//Console.WriteLine(ValidAnagramProblem.IsAnagram("aacc", "ccac"));
Console.WriteLine(ArrangingCoinsProblem.ArrangeCoins(5));
